import type { AppDefinition } from "./types";

export const cloudApps: AppDefinition[] = [
  {
    id: "datadog",
    name: "Datadog",
    icon: "/icons/datadog.svg",
    darkIcon: "/icons/datadog-light.svg",
    description: "Monitoring, APM, logs, and infrastructure metrics.",
    connectionMethod: { type: "cloud_only" },
    available: false,
  },
  {
    id: "outlook-mail",
    name: "Outlook Mail",
    icon: "/icons/outlook-mail.svg",
    description: "Read, compose, and send emails via Microsoft Outlook.",
    connectionMethod: { type: "cloud_only" },
    available: false,
  },
  {
    id: "outlook-calendar",
    name: "Outlook Calendar",
    icon: "/icons/outlook-calendar.svg",
    description: "View and manage calendar events in Microsoft Outlook.",
    connectionMethod: { type: "cloud_only" },
    available: false,
  },
  {
    id: "microsoft-word",
    name: "Microsoft Word",
    icon: "/icons/microsoft-word.svg",
    description:
      "Read and edit Word documents stored in OneDrive and SharePoint.",
    connectionMethod: { type: "cloud_only" },
    available: false,
  },
  {
    id: "microsoft-onenote",
    name: "Microsoft OneNote",
    icon: "/icons/microsoft-onenote.svg",
    description:
      "Read and manage notebooks, sections, and pages in Microsoft OneNote.",
    connectionMethod: { type: "cloud_only" },
    available: false,
  },
  {
    id: "aws-role",
    name: "AWS Role",
    icon: "/icons/aws.svg",
    darkIcon: "/icons/aws-light.svg",
    description:
      "Connect via IAM AssumeRole with temporary credentials and per-agent permissions.",
    connectionMethod: { type: "cloud_only" },
    available: false,
  },
  {
    id: "affinity",
    name: "Affinity",
    icon: "/icons/affinity.svg",
    description:
      "Manage relationships, deals, and interactions in Affinity CRM.",
    connectionMethod: { type: "cloud_only" },
    available: false,
  },
  {
    id: "zoom",
    name: "Zoom",
    icon: "/icons/zoom.svg",
    description: "Meetings, webinars, and cloud recordings.",
    connectionMethod: { type: "cloud_only" },
    available: false,
  },
  {
    id: "sentry",
    name: "Sentry",
    icon: "/icons/sentry.svg",
    darkIcon: "/icons/sentry-light.svg",
    description:
      "Error tracking, performance monitoring, and issue management.",
    connectionMethod: { type: "cloud_only" },
    available: false,
  },
  {
    id: "hubspot",
    name: "HubSpot",
    icon: "/icons/hubspot.svg",
    description: "CRM contacts, companies, deals, and tickets.",
    connectionMethod: { type: "cloud_only" },
    available: false,
  },
  {
    id: "linear",
    name: "Linear",
    icon: "/icons/linear.svg",
    darkIcon: "/icons/linear-light.svg",
    description: "Issues, projects, teams, and product development workflows.",
    connectionMethod: { type: "cloud_only" },
    available: false,
  },
  {
    id: "attio",
    name: "Attio",
    icon: "/icons/attio.svg",
    darkIcon: "/icons/attio-light.svg",
    description: "Contacts, companies, deals, lists, notes, and tasks.",
    connectionMethod: { type: "cloud_only" },
    available: false,
  },
  {
    id: "x",
    name: "X",
    icon: "/icons/x.svg",
    darkIcon: "/icons/x-light.svg",
    description: "Posts, timelines, DMs, and account management.",
    connectionMethod: { type: "cloud_only" },
    available: false,
  },
  {
    id: "fathom",
    name: "Fathom",
    icon: "/icons/fathom.svg",
    darkIcon: "/icons/fathom-light.svg",
    description: "AI meeting notes: recordings, transcripts, and summaries.",
    connectionMethod: { type: "cloud_only" },
    available: false,
  },
  {
    id: "slack",
    name: "Slack",
    icon: "/icons/slack.svg",
    description: "Channels, messages, people, and reactions in your workspace.",
    connectionMethod: { type: "cloud_only" },
    available: false,
  },
];
