import type { AppPermissionDefinition } from "./types";

export const gitlabPermissions: AppPermissionDefinition = {
  provider: "gitlab",
  groups: [
    {
      category: "read",
      tools: [
        {
          id: "list_projects",
          name: "List projects",
          description: "List projects accessible to the authenticated user",
          hostPattern: "gitlab.com",
          pathPattern: "/api/v4/projects",
          method: "GET",
        },
        {
          id: "get_project",
          name: "Read project",
          description: "Get project details, files, and metadata",
          hostPattern: "gitlab.com",
          pathPattern: "/api/v4/projects/*",
          method: "GET",
        },
        {
          id: "list_issues",
          name: "List issues",
          description: "List issues in a project",
          hostPattern: "gitlab.com",
          pathPattern: "/api/v4/projects/*/issues",
          method: "GET",
        },
        {
          id: "get_issue",
          name: "Get issue",
          description: "Get a single issue",
          hostPattern: "gitlab.com",
          pathPattern: "/api/v4/projects/*/issues/*",
          method: "GET",
        },
        {
          id: "list_merge_requests",
          name: "List merge requests",
          description: "List merge requests in a project",
          hostPattern: "gitlab.com",
          pathPattern: "/api/v4/projects/*/merge_requests",
          method: "GET",
        },
        {
          id: "get_merge_request",
          name: "Get merge request",
          description: "Get a single merge request",
          hostPattern: "gitlab.com",
          pathPattern: "/api/v4/projects/*/merge_requests/*",
          method: "GET",
        },
        {
          id: "list_branches",
          name: "List branches",
          description: "List repository branches",
          hostPattern: "gitlab.com",
          pathPattern: "/api/v4/projects/*/repository/branches",
          method: "GET",
        },
      ],
    },
    {
      category: "write",
      wildcard: {
        id: "write_all",
        name: "All write operations",
        description:
          "Create, update, delete, and merge issues, merge requests, branches, and comments",
        hostPattern: "gitlab.com",
        pathPattern: "/api/v4/*",
        methods: ["POST", "PUT", "PATCH", "DELETE"],
      },
      tools: [
        {
          id: "create_issue",
          name: "Create issue",
          description: "Create a new issue in a project",
          hostPattern: "gitlab.com",
          pathPattern: "/api/v4/projects/*/issues",
          method: "POST",
        },
        {
          id: "update_issue",
          name: "Update issue",
          description: "Update an issue in a project",
          hostPattern: "gitlab.com",
          pathPattern: "/api/v4/projects/*/issues/*",
          method: "PUT",
        },
        {
          id: "create_merge_request",
          name: "Create merge request",
          description: "Create a new merge request",
          hostPattern: "gitlab.com",
          pathPattern: "/api/v4/projects/*/merge_requests",
          method: "POST",
        },
        {
          id: "update_merge_request",
          name: "Update merge request",
          description: "Update a merge request",
          hostPattern: "gitlab.com",
          pathPattern: "/api/v4/projects/*/merge_requests/*",
          method: "PUT",
        },
        {
          id: "merge_merge_request",
          name: "Merge merge request",
          description: "Accept and merge a merge request",
          hostPattern: "gitlab.com",
          pathPattern: "/api/v4/projects/*/merge_requests/*/merge",
          method: "PUT",
        },
        {
          id: "create_issue_note",
          name: "Comment on issue",
          description: "Add a comment to an issue",
          hostPattern: "gitlab.com",
          pathPattern: "/api/v4/projects/*/issues/*/notes",
          method: "POST",
        },
        {
          id: "create_mr_note",
          name: "Comment on merge request",
          description: "Add a comment to a merge request",
          hostPattern: "gitlab.com",
          pathPattern: "/api/v4/projects/*/merge_requests/*/notes",
          method: "POST",
        },
        {
          id: "create_branch",
          name: "Create branch",
          description: "Create a new branch",
          hostPattern: "gitlab.com",
          pathPattern: "/api/v4/projects/*/repository/branches",
          method: "POST",
        },
        {
          id: "delete_branch",
          name: "Delete branch",
          description: "Delete a git branch",
          hostPattern: "gitlab.com",
          pathPattern: "/api/v4/projects/*/repository/branches/*",
          method: "DELETE",
        },
      ],
    },
  ],
};
