import type { AppPermissionDefinition } from "./types";

export const gmailPermissions: AppPermissionDefinition = {
  provider: "gmail",
  groups: [
    {
      category: "read",
      wildcard: {
        id: "read_all",
        name: "All read operations",
        description:
          "Search, read, and list emails, threads, drafts, labels, and settings",
        hostPattern: "gmail.googleapis.com",
        pathPattern: "/gmail/v1/*",
        method: "GET",
      },
      tools: [
        {
          id: "search_messages",
          name: "Search messages",
          description: "Search and list messages matching a query",
          hostPattern: "gmail.googleapis.com",
          pathPattern: "/gmail/v1/users/*/messages",
          method: "GET",
        },
        {
          id: "get_message",
          name: "Read message",
          description: "Retrieve a specific email message",
          hostPattern: "gmail.googleapis.com",
          pathPattern: "/gmail/v1/users/*/messages/*",
          method: "GET",
        },
        {
          id: "search_threads",
          name: "Search threads",
          description: "Search for threads matching a query",
          hostPattern: "gmail.googleapis.com",
          pathPattern: "/gmail/v1/users/*/threads",
          method: "GET",
        },
        {
          id: "get_thread",
          name: "Read thread",
          description: "Retrieve a specific email thread",
          hostPattern: "gmail.googleapis.com",
          pathPattern: "/gmail/v1/users/*/threads/*",
          method: "GET",
        },
        {
          id: "list_drafts",
          name: "List drafts",
          description: "List and read draft emails",
          hostPattern: "gmail.googleapis.com",
          pathPattern: "/gmail/v1/users/*/drafts",
          method: "GET",
        },
        {
          id: "list_labels",
          name: "List labels",
          description: "List all labels in the mailbox",
          hostPattern: "gmail.googleapis.com",
          pathPattern: "/gmail/v1/users/*/labels",
          method: "GET",
        },
      ],
    },
    {
      category: "write",
      wildcard: {
        id: "write_all",
        name: "All write operations",
        description:
          "Send, import, create drafts, modify labels, trash, and delete emails and threads",
        hostPattern: "gmail.googleapis.com",
        pathPattern: "/gmail/v1/*",
        // Media-carrying writes (send/insert/import/draft with an attachment)
        // hit the /upload/ endpoint on the same host — cover it so the
        // gate-all switch has no upload-shaped hole.
        aliasPatterns: ["/upload/gmail/v1/*"],
        methods: ["POST", "PUT", "PATCH", "DELETE"],
      },
      tools: [
        {
          id: "send_email",
          name: "Send email",
          description: "Send email on your behalf",
          hostPattern: "gmail.googleapis.com",
          pathPattern: "/gmail/v1/users/*/messages/send",
          method: "POST",
        },
        {
          id: "create_draft",
          name: "Create draft",
          description: "Create a new draft email",
          hostPattern: "gmail.googleapis.com",
          pathPattern: "/gmail/v1/users/*/drafts",
          method: "POST",
        },
        {
          id: "send_draft",
          name: "Send draft",
          description: "Send an existing draft email",
          hostPattern: "gmail.googleapis.com",
          pathPattern: "/gmail/v1/users/*/drafts/send",
          method: "POST",
        },
        {
          id: "modify_message",
          name: "Modify message",
          description: "Add or remove labels on a message",
          hostPattern: "gmail.googleapis.com",
          pathPattern: "/gmail/v1/users/*/messages/*/modify",
          method: "POST",
        },
        {
          id: "trash_message",
          name: "Trash message",
          description: "Move a message to trash",
          hostPattern: "gmail.googleapis.com",
          pathPattern: "/gmail/v1/users/*/messages/*/trash",
          method: "POST",
        },
        {
          id: "delete_draft",
          name: "Delete draft",
          description: "Permanently delete a draft email",
          hostPattern: "gmail.googleapis.com",
          pathPattern: "/gmail/v1/users/*/drafts/*",
          method: "DELETE",
        },
        {
          id: "batch_modify_messages",
          name: "Batch modify messages",
          description:
            "Add or remove labels on many messages at once (e.g. move the whole inbox to trash)",
          hostPattern: "gmail.googleapis.com",
          pathPattern: "/gmail/v1/users/*/messages/batchModify",
          method: "POST",
        },
        {
          id: "batch_delete_messages",
          name: "Batch delete messages",
          description: "Permanently delete many messages at once",
          hostPattern: "gmail.googleapis.com",
          pathPattern: "/gmail/v1/users/*/messages/batchDelete",
          method: "POST",
        },
        {
          id: "delete_message",
          name: "Delete message",
          description: "Permanently delete a single message (bypasses trash)",
          hostPattern: "gmail.googleapis.com",
          pathPattern: "/gmail/v1/users/*/messages/*",
          method: "DELETE",
        },
        {
          id: "untrash_message",
          name: "Untrash message",
          description: "Remove a message from trash",
          hostPattern: "gmail.googleapis.com",
          pathPattern: "/gmail/v1/users/*/messages/*/untrash",
          method: "POST",
        },
        {
          id: "insert_message",
          name: "Insert message",
          description: "Insert a raw message directly into the mailbox",
          hostPattern: "gmail.googleapis.com",
          pathPattern: "/gmail/v1/users/*/messages",
          method: "POST",
        },
        {
          id: "import_message",
          name: "Import message",
          description: "Import a raw message into the mailbox (as if received)",
          hostPattern: "gmail.googleapis.com",
          pathPattern: "/gmail/v1/users/*/messages/import",
          method: "POST",
        },
        {
          id: "trash_thread",
          name: "Trash thread",
          description: "Move an entire thread to trash",
          hostPattern: "gmail.googleapis.com",
          pathPattern: "/gmail/v1/users/*/threads/*/trash",
          method: "POST",
        },
        {
          id: "untrash_thread",
          name: "Untrash thread",
          description: "Remove an entire thread from trash",
          hostPattern: "gmail.googleapis.com",
          pathPattern: "/gmail/v1/users/*/threads/*/untrash",
          method: "POST",
        },
        {
          id: "modify_thread",
          name: "Modify thread",
          description: "Add or remove labels on an entire thread",
          hostPattern: "gmail.googleapis.com",
          pathPattern: "/gmail/v1/users/*/threads/*/modify",
          method: "POST",
        },
        {
          id: "delete_thread",
          name: "Delete thread",
          description: "Permanently delete an entire thread (bypasses trash)",
          hostPattern: "gmail.googleapis.com",
          pathPattern: "/gmail/v1/users/*/threads/*",
          method: "DELETE",
        },
        {
          id: "update_draft",
          name: "Update draft",
          description: "Replace the content of an existing draft",
          hostPattern: "gmail.googleapis.com",
          pathPattern: "/gmail/v1/users/*/drafts/*",
          method: "PUT",
        },
      ],
    },
  ],
};
