import type { AppPermissionDefinition } from "./types";

export const supabasePermissions: AppPermissionDefinition = {
  provider: "supabase",
  groups: [
    {
      category: "read",
      tools: [
        {
          id: "list_organizations",
          name: "List organizations",
          description: "List organizations the user belongs to",
          hostPattern: "api.supabase.com",
          pathPattern: "/v1/organizations",
          method: "GET",
        },
        {
          id: "list_projects",
          name: "List projects",
          description: "List all projects across organizations",
          hostPattern: "api.supabase.com",
          pathPattern: "/v1/projects",
          method: "GET",
        },
        {
          id: "get_project",
          name: "Get project",
          description: "Retrieve details of a specific project",
          hostPattern: "api.supabase.com",
          pathPattern: "/v1/projects/*",
          method: "GET",
        },
        {
          id: "get_database_config",
          name: "Get database config",
          description: "View database and pooler configuration",
          hostPattern: "api.supabase.com",
          pathPattern: "/v1/projects/*/config/database/*",
          method: "GET",
        },
        {
          id: "get_auth_config",
          name: "Get auth config",
          description: "View authentication settings and providers",
          hostPattern: "api.supabase.com",
          pathPattern: "/v1/projects/*/config/auth",
          method: "GET",
        },
        {
          id: "get_postgrest_config",
          name: "Get PostgREST config",
          description: "View PostgREST API configuration",
          hostPattern: "api.supabase.com",
          pathPattern: "/v1/projects/*/postgrest",
          method: "GET",
        },
        {
          id: "list_functions",
          name: "List edge functions",
          description: "List all edge functions in a project",
          hostPattern: "api.supabase.com",
          pathPattern: "/v1/projects/*/functions",
          method: "GET",
        },
        {
          id: "list_secrets",
          name: "List secrets",
          description: "List API keys and project secrets",
          hostPattern: "api.supabase.com",
          pathPattern: "/v1/projects/*/secrets",
          method: "GET",
        },
        {
          id: "list_storage_buckets",
          name: "List storage buckets",
          description: "List storage buckets in a project",
          hostPattern: "api.supabase.com",
          pathPattern: "/v1/projects/*/storage/buckets",
          method: "GET",
        },
      ],
    },
    {
      category: "write",
      wildcard: {
        id: "write_all",
        name: "All write operations",
        description:
          "Run SQL and create or modify projects, edge functions, and secrets",
        hostPattern: "api.supabase.com",
        pathPattern: "/v1/*",
        methods: ["POST", "PUT", "PATCH", "DELETE"],
      },
      tools: [
        {
          id: "run_query",
          name: "Run SQL query",
          description: "Execute a SQL query against the database",
          hostPattern: "api.supabase.com",
          pathPattern: "/v1/projects/*/database/query",
          method: "POST",
        },
        {
          id: "create_project",
          name: "Create project",
          description: "Create a new Supabase project",
          hostPattern: "api.supabase.com",
          pathPattern: "/v1/projects",
          method: "POST",
        },
        {
          id: "update_auth_config",
          name: "Update auth config",
          description: "Modify authentication settings",
          hostPattern: "api.supabase.com",
          pathPattern: "/v1/projects/*/config/auth",
          method: "PATCH",
        },
        {
          id: "create_secrets",
          name: "Create or update secrets",
          description: "Add or update project secrets",
          hostPattern: "api.supabase.com",
          pathPattern: "/v1/projects/*/secrets",
          method: "POST",
        },
        {
          id: "create_function",
          name: "Create edge function",
          description: "Deploy a new edge function",
          hostPattern: "api.supabase.com",
          pathPattern: "/v1/projects/*/functions",
          method: "POST",
        },
        {
          id: "update_function",
          name: "Update edge function",
          description: "Update an existing edge function",
          hostPattern: "api.supabase.com",
          pathPattern: "/v1/projects/*/functions/*",
          method: "PATCH",
        },
        {
          id: "delete_function",
          name: "Delete edge function",
          description: "Remove an edge function",
          hostPattern: "api.supabase.com",
          pathPattern: "/v1/projects/*/functions/*",
          method: "DELETE",
        },
      ],
    },
  ],
};
