import type { AppPermissionDefinition } from "./types";

export const awsPermissions: AppPermissionDefinition = {
  provider: "aws",
  groups: [
    {
      category: "read",
      tools: [
        {
          id: "s3_list_buckets",
          name: "List S3 buckets",
          description: "List all S3 buckets in the account",
          hostPattern: "s3.*.amazonaws.com",
          pathPattern: "/",
          method: "GET",
        },
        {
          id: "s3_read_objects",
          name: "Read S3 objects",
          description: "List and download objects from S3 buckets",
          hostPattern: "s3.*.amazonaws.com",
          pathPattern: "/*",
          method: "GET",
        },
        {
          id: "lambda_list_functions",
          name: "List Lambda functions",
          description: "List all Lambda functions in the account",
          hostPattern: "lambda.*.amazonaws.com",
          pathPattern: "/2015-03-31/functions",
          method: "GET",
        },
        {
          id: "lambda_get_function",
          name: "Get Lambda function",
          description: "Get configuration and details of a Lambda function",
          hostPattern: "lambda.*.amazonaws.com",
          pathPattern: "/2015-03-31/functions/*",
          method: "GET",
        },
        {
          id: "ec2_access",
          name: "Access EC2",
          description: "Describe and manage EC2 instances and resources",
          hostPattern: "ec2.*.amazonaws.com",
          pathPattern: "/*",
          method: "POST",
        },
        {
          id: "cloudwatch_logs_access",
          name: "Access CloudWatch Logs",
          description: "Read log groups, streams, and log events",
          hostPattern: "logs.*.amazonaws.com",
          pathPattern: "/*",
          method: "POST",
        },
        {
          id: "iam_access",
          name: "Access IAM",
          description: "List and describe users, roles, and policies",
          hostPattern: "iam.amazonaws.com",
          pathPattern: "/*",
          method: "POST",
        },
        {
          id: "sts_access",
          name: "Access STS",
          description: "Get caller identity and assume roles",
          hostPattern: "sts.*.amazonaws.com",
          pathPattern: "/*",
          method: "POST",
        },
      ],
    },
    {
      category: "write",
      tools: [
        {
          id: "s3_upload",
          name: "Upload to S3",
          description: "Upload and write objects to S3 buckets",
          hostPattern: "s3.*.amazonaws.com",
          pathPattern: "/*",
          method: "PUT",
        },
        {
          id: "s3_delete",
          name: "Delete from S3",
          description: "Delete objects from S3 buckets",
          hostPattern: "s3.*.amazonaws.com",
          pathPattern: "/*",
          method: "DELETE",
        },
        {
          id: "lambda_invoke",
          name: "Invoke Lambda function",
          description: "Execute a Lambda function",
          hostPattern: "lambda.*.amazonaws.com",
          pathPattern: "/2015-03-31/functions/*/invocations",
          method: "POST",
        },
        {
          id: "lambda_delete",
          name: "Delete Lambda function",
          description: "Delete a Lambda function",
          hostPattern: "lambda.*.amazonaws.com",
          pathPattern: "/2015-03-31/functions/*",
          method: "DELETE",
        },
        {
          id: "dynamodb_access",
          name: "Access DynamoDB",
          description: "Read, write, and manage DynamoDB tables and items",
          hostPattern: "dynamodb.*.amazonaws.com",
          pathPattern: "/*",
          method: "POST",
        },
        {
          id: "ses_send",
          name: "Send emails via SES",
          description: "Send emails using Simple Email Service",
          hostPattern: "email.*.amazonaws.com",
          pathPattern: "/v2/email/outbound-emails",
          method: "POST",
        },
        {
          id: "secrets_manager_access",
          name: "Access Secrets Manager",
          description: "Read, create, and manage secrets",
          hostPattern: "secretsmanager.*.amazonaws.com",
          pathPattern: "/*",
          method: "POST",
        },
        {
          id: "cloudformation_access",
          name: "Access CloudFormation",
          description: "Create, update, and manage CloudFormation stacks",
          hostPattern: "cloudformation.*.amazonaws.com",
          pathPattern: "/*",
          method: "POST",
        },
      ],
    },
  ],
};
