import type { AppPermissionDefinition } from "./types";

export const cloudflarePermissions: AppPermissionDefinition = {
  provider: "cloudflare",
  groups: [
    {
      category: "read",
      tools: [
        {
          id: "list_zones",
          name: "List zones",
          description: "List all DNS zones (domains)",
          hostPattern: "api.cloudflare.com",
          pathPattern: "/client/v4/zones",
          method: "GET",
        },
        {
          id: "get_zone",
          name: "Get zone",
          description: "Get details for a specific zone",
          hostPattern: "api.cloudflare.com",
          pathPattern: "/client/v4/zones/*",
          method: "GET",
        },
        {
          id: "list_dns_records",
          name: "List DNS records",
          description: "List DNS records for a zone",
          hostPattern: "api.cloudflare.com",
          pathPattern: "/client/v4/zones/*/dns_records",
          method: "GET",
        },
        {
          id: "list_workers",
          name: "List Workers",
          description: "List deployed Workers scripts",
          hostPattern: "api.cloudflare.com",
          pathPattern: "/client/v4/accounts/*/workers/scripts",
          method: "GET",
        },
        {
          id: "list_kv_namespaces",
          name: "List KV namespaces",
          description: "List Workers KV namespaces",
          hostPattern: "api.cloudflare.com",
          pathPattern: "/client/v4/accounts/*/storage/kv/namespaces",
          method: "GET",
        },
        {
          id: "list_d1_databases",
          name: "List D1 databases",
          description: "List D1 SQL databases",
          hostPattern: "api.cloudflare.com",
          pathPattern: "/client/v4/accounts/*/d1/database",
          method: "GET",
        },
        {
          id: "list_r2_buckets",
          name: "List R2 buckets",
          description: "List R2 storage buckets",
          hostPattern: "api.cloudflare.com",
          pathPattern: "/client/v4/accounts/*/r2/buckets",
          method: "GET",
        },
        {
          id: "list_pages_projects",
          name: "List Pages projects",
          description: "List Cloudflare Pages projects",
          hostPattern: "api.cloudflare.com",
          pathPattern: "/client/v4/accounts/*/pages/projects",
          method: "GET",
        },
      ],
    },
    {
      category: "write",
      tools: [
        {
          id: "create_dns_record",
          name: "Create DNS record",
          description: "Add a new DNS record to a zone",
          hostPattern: "api.cloudflare.com",
          pathPattern: "/client/v4/zones/*/dns_records",
          method: "POST",
        },
        {
          id: "update_dns_record",
          name: "Update DNS record",
          description: "Update an existing DNS record",
          hostPattern: "api.cloudflare.com",
          pathPattern: "/client/v4/zones/*/dns_records/*",
          method: "PUT",
        },
        {
          id: "delete_dns_record",
          name: "Delete DNS record",
          description: "Delete a DNS record",
          hostPattern: "api.cloudflare.com",
          pathPattern: "/client/v4/zones/*/dns_records/*",
          method: "DELETE",
        },
        {
          id: "deploy_worker",
          name: "Deploy Worker",
          description: "Upload and deploy a Workers script",
          hostPattern: "api.cloudflare.com",
          pathPattern: "/client/v4/accounts/*/workers/scripts/*",
          method: "PUT",
        },
        {
          id: "delete_worker",
          name: "Delete Worker",
          description: "Delete a Workers script",
          hostPattern: "api.cloudflare.com",
          pathPattern: "/client/v4/accounts/*/workers/scripts/*",
          method: "DELETE",
        },
        {
          id: "write_kv",
          name: "Write KV value",
          description: "Write a key-value pair to KV",
          hostPattern: "api.cloudflare.com",
          pathPattern: "/client/v4/accounts/*/storage/kv/namespaces/*/values/*",
          method: "PUT",
        },
        {
          id: "query_d1",
          name: "Query D1 database",
          description: "Execute SQL against a D1 database",
          hostPattern: "api.cloudflare.com",
          pathPattern: "/client/v4/accounts/*/d1/database/*/query",
          method: "POST",
        },
        {
          id: "purge_cache",
          name: "Purge cache",
          description: "Purge cached content for a zone",
          hostPattern: "api.cloudflare.com",
          pathPattern: "/client/v4/zones/*/purge_cache",
          method: "POST",
        },
      ],
    },
  ],
};
