import type { AppPermissionDefinition } from "./types";

export const notionPermissions: AppPermissionDefinition = {
  provider: "notion",
  groups: [
    {
      category: "read",
      tools: [
        {
          id: "search",
          name: "Search pages & databases",
          description: "Search across workspace content",
          hostPattern: "api.notion.com",
          pathPattern: "/v1/search",
          method: "POST",
        },
        {
          id: "get_page",
          name: "Get page",
          description: "Retrieve a specific page",
          hostPattern: "api.notion.com",
          pathPattern: "/v1/pages/*",
          method: "GET",
        },
        {
          id: "get_block_children",
          name: "Get block children",
          description: "Retrieve content blocks of a page",
          hostPattern: "api.notion.com",
          pathPattern: "/v1/blocks/*/children",
          method: "GET",
        },
        {
          id: "query_database",
          name: "Query database",
          description: "Query a database with filters and sorts",
          hostPattern: "api.notion.com",
          pathPattern: "/v1/databases/*/query",
          method: "POST",
        },
        {
          id: "get_database",
          name: "Get database",
          description: "Retrieve a database schema",
          hostPattern: "api.notion.com",
          pathPattern: "/v1/databases/*",
          method: "GET",
        },
        {
          id: "list_comments",
          name: "List comments",
          description: "Retrieve comments on a page or block",
          hostPattern: "api.notion.com",
          pathPattern: "/v1/comments",
          method: "GET",
        },
        {
          id: "list_users",
          name: "List users",
          description: "List all users in the workspace",
          hostPattern: "api.notion.com",
          pathPattern: "/v1/users",
          method: "GET",
        },
      ],
    },
    {
      category: "write",
      tools: [
        {
          id: "create_page",
          name: "Create page",
          description: "Create a new page in a parent page or database",
          hostPattern: "api.notion.com",
          pathPattern: "/v1/pages",
          method: "POST",
        },
        {
          id: "update_page",
          name: "Update page",
          description: "Update page properties",
          hostPattern: "api.notion.com",
          pathPattern: "/v1/pages/*",
          method: "PATCH",
        },
        {
          id: "append_blocks",
          name: "Append blocks",
          description: "Add content blocks to a page",
          hostPattern: "api.notion.com",
          pathPattern: "/v1/blocks/*/children",
          method: "PATCH",
        },
        {
          id: "update_block",
          name: "Update block",
          description: "Update an existing content block",
          hostPattern: "api.notion.com",
          pathPattern: "/v1/blocks/*",
          method: "PATCH",
        },
        {
          id: "delete_block",
          name: "Delete block",
          description: "Archive a content block",
          hostPattern: "api.notion.com",
          pathPattern: "/v1/blocks/*",
          method: "DELETE",
        },
        {
          id: "create_comment",
          name: "Create comment",
          description: "Add a comment to a page or discussion",
          hostPattern: "api.notion.com",
          pathPattern: "/v1/comments",
          method: "POST",
        },
      ],
    },
  ],
};
